export enum GenresEnum {
    FICTION = "Fiction",
    NON_FICTION = "Non-Fiction",
    MYSTERY = "Mystery",
    CRIME = "Crime",
    FANTASY = "Fantasy",
    SCIENCE_FICTION = "Sci-Fi",
    BIOGRAPHY = "Biography",
    HISTORY = "History",
    ROMANCE = "Romance",
    THRILLER = "Thriller",
    HORROR = "Horror",
    SELF_HELP = "Self-Help",
    POETRY = "Poetry",
    CLASSIC = "Classic",
    ADVENTURE = "Adventure",
    CHILDREN = "Children",
}